sonar.projectKey=Daysof1_AfroDB
sonar.organization=daysof1

sonar.sources=backend,frontend,app_movil

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.expo/**,**/coverage/**